start cmd /k "cd discovery-server && mvn spring-boot:run"
start cmd /k "cd movie-catalog-service && mvn spring-boot:run"
start cmd /k "cd movie-info-service && mvn spring-boot:run"
start cmd /k "cd ratings-data-service && mvn spring-boot:run"
start cmd /k "cd top-ratings-grpc-service && mvn spring-boot:run"